version: '3.9'

services:

  db:
    image: postgres:11.0-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB_PORT=${POSTGRES_DB_PORT}
      - POSTGRES_DB_HOST=db
  
  redis:
    image: redis:latest

  web:
    build: ./src
    command: ./run_django.sh
    volumes:
      - .:/app/
      - ./src/media/:/app/src/media/
    ports:
     - "8000:8000"
    env_file:
      - ./src/project/.env
    depends_on:
      - db
      - redis

  rqworker:
    build: ./src
    command: ./run_rq.sh
    volumes:
      - .:/app/    
    depends_on:
      - web
      - redis    
