# Generated by Django 4.0 on 2022-04-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя файла'),
        ),
    ]
