# Generated by Django 4.0 on 2022-04-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_fileupload_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='content_type',
            field=models.CharField(blank=True, max_length=128, verbose_name='Тип файла'),
        ),
    ]
